version: '3'

services:
  app:
    container_name: allsell-admin
    build:
      context: ./
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./logs:/app/logs
